version: '3.7'

services:
  postgres:
    image: postgres:latest
    container_name: postgres-keycloak
    environment:
      POSTGRES_USER: keycloak
      POSTGRES_PASSWORD: keycloak
      POSTGRES_DB: keycloak
    volumes:
      - postgres-data:/var/lib/postgresql/data
    networks:
      - keycloak-network
    ports:
      - "5432:5432"

  keycloak:
    image: quay.io/keycloak/keycloak:latest
    container_name: keycloak
    environment:
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
      KC_DB: postgres
      KC_DB_URL: jdbc:postgresql://postgres:5432/keycloak
      KC_DB_USERNAME: keycloak
      KC_DB_PASSWORD: keycloak
    ports:
      - "8080:8080"
    networks:
      - keycloak-network
    depends_on:
      - postgres
    command:
      - start-dev

  aplicacoes:
    build: .
    ports:
      - "8081:8081"
      - "8082:8082"
      - "8083:8083"
    environment:
      - TZ=America/Sao_Paulo
    restart: always

volumes:
  postgres-data:

networks:
  keycloak-network:
    driver: bridge
